mode: production
base_url: /sign
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
context:
  data:
    default_interval: 3600
    
meta:
    page_width: "1920px"
    page_height: "1080px"
    nodemeta: meta.yaml
    created: !!timestamp 2010-01-01 00:00:00
    author: Mark Stillwell
    extends: base.j2
    default_block: main
